var COMMANDS = {
    CONNECT: 1,
    SEND_MESSAGE: 2,
    NICKNAME: 3,
    ERROR: 4,
    CONNECTED: 5,
    USER_DATA: 6,
    TYPING: 7,
    STOP_TYPING: 8,
    USER_CONNECTED: 9,
    USER_DISCONNECTED: 10,
    RECEIVED_MESSAGE: 11,
    DISCONNECT: 12
};